

const config = {
  "name": "nhayv3",
  "aliases": ["dcm"],
  "description": "",
  "usage": "",
  "cooldown": 3,
  "permissions": [2],
  "credits": "WaifuCat",
  "extra": {}
};

const list = [
  "cha thanh phú đến nè bọn ngu🤣",
  "cmm lên gõ vs cha tp nè 🤣⚡",
  "Lũ đú hết thời lên đây xưng danh với ai",
   "thẩm du cái lồn má m lên :))",
  "con đĩ cãi cùn",
  "địt bà nội sư gia nhà m =))",
  "úi úi",
  "nhanh lên con chó lồn khai khắm=))",
  "sao con đĩ mẹ ày gà vậy",
  "địt lồn mẹ mày",
  "dập cặc thằng cha mày liền",
  "Cầm đinh ba đâm lòi cuống họng đĩ mẹ mày liền",
  "Con thú đú",
  "lòi lồn chiến sĩ rồi à",
  "sao không mạnh mẽ lên",
  "khép lép vậy",
  "sợ hãi rồi à",
  "Lẹ lên con điếm thúi",
  "con đĩ mồ coi ăn hôi",
  "thế nào rồi",
  "sợ anh mày chưa",
  "anh mày bá sàn mà",
  "sao m chối hoài",
  "chối là con má m die",
  "ngu thì ngu vừa thôi=))",
  "không t đâm chết thằng cha mày",
  "óc chó dữ",
  "lồn mẹ mày",
  "điếm thúi ơi=))",
  "đừng rớt nhây nhó:3",
  "thấy sao rùi:3",
  "Bede sủa tiếng nghe choiw",
  "Cặc Cặc Cặc",
  "Lồn Lồn Lồn",
  "=))",
  "Thấy anh nhây bá ko",
  "quá bá mà",
  "sao lại anh được",
  "khép đuôi xin tha đê",
  "Rủa đĩ má m die",
  "Ngồi nhây tới đêm trăng tròn nè=))",
  "Nhây sao lại anh",
  "Bóng sida",
  "bede dập cu ơi=))",
  "nhắm chửi lại anh không=))",
  "lẹ lên con đĩ",
  "điếm thúi ăn hôi ơi:))",
  "Lên xem còn tài cán gì không nào",
  "Sao mà xạo lồn",
  "Dân va 2023 à",
  "Chỉ có vậy thôi sao",
  "mày làm được gì không😤",
  "hay chỉ biết phản kháng🤭=))",
  "tk cu bé phản kháng di😏?",
  "con đĩ cave luôn khảng phán đi🥺?",
  "bị chửi nên không phản kháng à😀?",
 "con cave và tk cu bé hợp nhề😏👉",
 "2 con bede không phản kháng được à😋",
"2 con bede sợ anh rồi:))🙃",
"chạy về mách mẹ à 2 con bede😗?",
"chạy về trốn dô cái lồn mẹ mày đi😍?",
"1 đứa bú lồn mẹ😎?",
"1 đứa bú cu cha😎?",
"bất hiếu cmnr:))😜",
"mày làm gì để anh sợ đi:))🤣?",
"mày có tý sát thương nào ko😂?",
"con đĩ mẹ mày ăn cứt cố đi🤣?",
"mày sợ anh à con chó ăn cứt:))?",
"anh win cmnr clm🤣",
"lũ cave cay cha cmnr😑",
"Cha mày tới đâu là lũ đú phải dè chừng",
"Đã ngu còn thích tỏ ra mình có trình hả cn thú ngu êy",
"Bởi vì mày làm gì có trình ?",
"Thể hiện mình có trình đi con chó ngu ngục ơi ",
"Sao mày sống mất dạy quá vậy bame mày khờ mà mày còn lười!",
"Sủa hăng hái lên sao dị đú đa đú đỡn xạo lồn tập đú mxh ",
"Lgbt xuất trận hả hay sao 🤔?",
"Đừng cay cú cha mà hóa rồ lên làm nét ",
"Nhìn lũ ngu dồn cha trong vô vọng kìa 😂",
"Ráng đi sắp win r đó lũ đú êy",
"Gần quin rồi ráng thêm sí nữa đi",
"Đừng rụng nhé lũ ngu",
"Trận này anh win rõ mà sao cưng chối ăng ẳng thế",
"Khi nào con hết xàm lồn vậy?",
"Sao con đú quá vậy con thú êy",
"Alo con còn sống kh đó",
"Hay bị hành quá nên sinh ra hoang tưởng ",
"Mày sủa hăng hái lên cn thú đú eye",
"Chậm chạp như rùa bò v",
"Hăngg máu lên chứ yếu kém quá",
"Gà mà hay xạo lồn quá vậy",
"Cưng sủa lên đi sao im r ",
"Cha cho im chưa hả cn thú ngu êy🤣",
"Thấy cha là xách giò chạy hả",
"Câm rồi à chán thế",
"Mày nín r hả",
"Sao nín r vậy",
"Hay bị mẹ gank rồi",
"Yếu kém quá cn thú ơi",
"Hay đuối rồi jar",
"Đuối r thì kêu cha cha tha cho",
"Sao pải cuốn cuồng lên thế🤣",
"Ai làm gì mà mếu r v",
"Cay cú kh làm đc gì à",
"Mếu máo rõ mà rồi sao nữa ht ngôn à ",
"Yếu kém v thú đú nhảm lồn đú ửa kiểu",
"Hay bị hành quá nên núp r",
"Sao v mặt căng v cay cha rồi hả 🤨🌶?",
"Cay cha rõ mà sao xạo lồn hả",
"Nhìn mày gõ như đống tro tàn cốt mã nhà mày để lại cho mày vậy á",
"Không được cay anh quá mà làm liều nghe chưa!",
"Đừng bị anh chửi nhiều quá mà tự ái nhảy lầu tự tử nhé",
"Đừng có lên mạng xã hội tạo nét mà bị anh hành là mếu máo đi cầu cứu ngay",
"Khi nào có trình r đọ với anh chứ trình không có mà sủa hăng ghê ta ",
"Cưng xạo lồn chứ làm gì có trình",
"Rồi sao nữa",
"Con điếm phò mã bị cha mày cầm cái cây chà bồn cầu cha chà nát lồn mày nè",
"Con thú ngu dốt bị cha mày hành cho đầu óc quay cuồng r à",
"Sao cay hả cay r làm được gì không hay chỉ được ngồi gõ nhảm bển 🌶",
"Cay mếu máo sao khóc rồi",
"Khóc r hả thương vậy",
"Thương cho con thú cay anh mà không làm được gì",
"Sao cho cầu cứu mà cầu cứu xog sao kh ai dám dô giúp ht vậy",
"Sống chi bần hèn quá v",
"Sao con đú mà con xạo lồn hả cn thú ngu êy",
"Cha mày chuyên hành lũ đú mà",
"Con sủa hăng máu lên ",
"Câm là cha mày gọi hồn mày như gọi đò",
"Con sơ hở là xạo lồn bịa chuyện ai xem",
"Nhìn con dị hợm quá vậy?",
"Con kiếp trước chắc sống phế lắm nhỉ",
"Qua kiếp này làm lại từ đầu mà sao ngu quá v",
"Cn thú cầm cái phím tắt ôm trong tuyệt vọng hả",
"Đú sao lại được hả cn ngồi ôm phím gõ dăm ba mấy cái ngôn xưa lắc xưa lơ ",
"Ai cứu mày được quả này",
"Cầu cứu lẹ đi🤣",
"Cha hóng nãy giờ nè🤣",
"Mày mà câm là cha mày win rõ nhé",
"Cha mày hóa thân thành hắc bạch vô thường cha mày bắt hồn đĩ mẹ mày xuống chầu diêm vương",
"Con chó mày hăng hái lên xem nào",
"Hay bị cha mày bón cho 1 kí hành dô mõm nên không dám sủa nữa",
"cái thứ con người mà não còn không có mà đòi đọ với ai🤣",
"Nhìn mặt mày như con tinh tinh đầu thai chuyển kiếp thành con người v🤣",
"Nhìn mặt mày là thấy 2 chữ phèn ngu😗",
"Đã nghèo đã phèn đã ngu đã dốt mà đòi hơn ai",
"Bản thân mình không làm được cho mình thì làm được cho ai",
"Sống như 1 con chó ngu dốt như lũ phèn ói chợ búa cầm dao múa kiếm",
"Sủa hăng hái lên chứ yếu kém quá cha mày hăng không nổi😉!",
"Gõ phím tắt để làm nét ai xem",
"Mày đi cầu cứu ai hả!?",
"Tao đố đứa nào dám dô cứu mày đấy",
"Đã ngu còn hay tạo nét",
"Cha mày tới là lũ ngu cũm pải dè chừng",
"Đã ngu còn đú thì phế mẹ đi",
"Cha đấng mxh mà🤔!",
"Cưng ganh tị với anh hả?",
"Cưng hăng hái với ai?",
"Sao con đuối rồi hả?",
"Chỉ được vậy thôi hả!",
"Còn chiêu nào không tung ra đi",
"Chứ thấy mấy cái chiêu trò phèn của mày đi trong ruột mày từ 7 kiếp r ",
"Bị cha mày hành nhiều quá nên sính ra hoa tưởng hả 🤨?!",
"Con sống ngu mà con hay tạo nét quá v cn thú ngu êy",
"Con thú ngu bị cha mày hành nhìu quá nên không dám sủa nữa à",
"Sao vậy yếu kém vậy hay đuối r hả đĩ gà mờ",
"Cha mày tới là lũ ngu cũm pải rén mà thôi", 
"Hăng lên xíu được không dọ",
"Nín hết rồi hả sao không hăng như ban đầu đê",
"Sao mấy cn thú đi theo bầy đàn bị cha mày hành tới mức mà pải núp hết rồi dị",
"Não mày bị chèn tinh trùng của thằng cha mày trổng hả?",
"Não tàn đến mức pải đi xin tha hả?",
"Não mày chứa toàn cứt của con chó nhà mày à",
"Sao mày không hăng hái nữa",
"Hay rớt rồi hả",
"Sao câm nín rồi 😑",
"Sủa hăng hái máu chiến lên nào",
"Yếu kém v con thú đú ngu êy",
"Sủa sao cho nghe lọt lỗ tai",
"Cha tới nè nhú lên diện kiến cha lẹ",
"Bame mày quỳ lạy kêu anh xin tha mà",
"Cốt cách như buồi gõ xàm gõ điên",
"Gõ sao lại tụi anh được hả lũ đú ",
"Đã ngu còn thích sỉ diện",
"Chó ngoan cục cưng hãy về với chủ đừng cắn bậy",
"Sống sang lên cho nết thanh tịnh",
"Sống dơ sồng hèn muôn đời bết",
"Còn sống thì nhú lên đú tiếp cho tụi anh chiêm ngưỡng",
"Tàn tạ từ nhân cách đến não bộ",
"Sống cho cuộc đời có tâm và có tầm",
"Ngu thì đừng phán vs ai nhé cn chó ghẻ ",
"Nghe 1 thời giảng sanh của cha mà tích đức",
"Sống như con chó ngu dốt đầu đường xó chợ",
"Ngồi xuống cha giảng đạo cho nghe nè",
"Nghèo bần hèn bị cha mày đứng trên đạp đầu lũ đú chúng mày cha đi lên ",
"Cay mếu máo cha mà chả làm được gì hả",
"Không được quay qua méc mẹ nghe chưa",
"Đã ngu còn thích thể hiện hả thk nhóc",
"Khi nào đủ trình r so với anh nghe chưa",
"Thân phận nghèo hèn đú ai xem ",
"Đú má mày tới tháng xịt nước máu kinh cho thk cha mày uống",
"Khi nào con có đủ tầm ảnh hưởng lên đứng với cha ",
"ê wavy giả bộ ngừng đi",
"Gõ ngôn lặp đi lặp lại ngôn 1 màu thì đừng gõ",
"Thứ yêu nghiệt xuống hạn nhân sanh",
"Sủa dơ cha mày cầm cái chổi nhét dô lồn m nè",
"Thứ súc sinh muốn tiến hóa thành người",
"Mày ngưng là má mày đột tử tới",
"Thú đú như mày làm cha bùn cười quá ",
"Khi nào có trình đú với anh nha",
"Sao chậm quá vậy?😂",
"Sủa hăng hái mạnh mẽ lên",
"Cốt cách thiên nga tâm hồn quỷ dữ 😈",
"Thân tàn ma dại",
"Con dốt ba mẹ mày đẻ ra con quái thai",
"Con thú cố tí đi",
"sồn hăng lên em",
"sao m yếu v",
"Cặc con",
"Sắp win r",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"não cứt cay cha m",
"sao thế tk não phẳng",
"Âm binh kìa ae🤣  ",
"Ê thằng đầu đinh  ",
"Ê chx tới tết  ",
"hăng lên con",
"sao m yếu ớt v🌶",
"chawin r cố lmj😘😘😫",
"sao kìa đuối à",
"căng lên chứ",
"tới sáng đi cục cưng của cha",
"clm bất ổn à",
"k nổi à",
" cố thằng đần di",
"sao mẹ mày bị t chém thế",
"đần vl",
"thái xin win trận này😂🤨",
"hoảng à",
"đúng mà",
"cãi à",
"mày còn gì hay hơn k",
"bắt chước kìa",
"mếu à thằng tam kì",
"sao mếu kìa",
"tao cho m chết chưa",
"va chạm lẹ đi🤪🤪",
"sao vậy",
"nhục rồi à",
"mạnh mẽ tí đi mà",
"cố đi",
"😛😛😛",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"sao mới 5p đã câm r",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó đi🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh eii",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"Khác gì ảo ửa đâu🤣🤣🤣  ",
"Nhìn mặt kìa  ",
"Dái chó à🐶😏🤣  ",
"Thằng lộ link🤣  ",
"Thằng cặc bé êy  ",
"Đr tí nữa ",
"chết cha nó sồn r  ",
"Đúng roi tiếp tục  ",
"Nhanh tí nữa  ",
"sCặc con  ",
"mày sủa đi nè😛  ",
"Nhanh tí nữa ",
"Chậm à😂  ",
"M cố mot tí nua😋 ",
"Là m win anh r",
"Thk bẻm đú🤣",
"Con chó cay à ",
"Cayyyyy:))))",
"sao câm z em 🤣🤣",
"Mày ngu mà đúng ko🤣🤣🤣",
"Ê nó cay kìa ae😗",
"Thằng óc chim ",
"là em sai lầm",
"Cay anh à🤣",
"Thằng dái lở🤣",
"m đang khiếp hãi à😆🤔",
"M ổn ko đó🤣",
"đụ mẹ m sủa lên đi",
"Nhìn cặc con cay kía🌶🤣",
"M ổn ko đó🤣",
"thk cặc óc cứt m sủa đi",
"đéo lên tao win nhé tk mặt lồnt",
"Clm m bất ổn à ",
"Mày chậm à",
"Dái lở ổn ko🤣",
"đéo lên tao win nhé tk mặt lồn",
"m câm t chặt đầu ba má m liền nè",
"con chó ngu đuối kìa ae🤔",
"thật maa",
"con đĩ mẹ mày bất lực vì bị tao chửi mà chỉ biết câm lặng:)))  ",
"làm màu mà bị tao chửi rung cái con cặc:)))  ",
"Mẹ mày bị tao đụ lòi hột le:)))  ",
"thằng bê đê ảo cặc đòi cân và cái kết:)))  ",
"con đĩ mẹ của mày thèm cứt tao dữ lắm:)))  ",
"bị tao chửi sảng cặc đéo dám care:)))  ",
"mạnh lên sao yếu đuối v con:)))  ",
"mày run cặc chưa con:)))  ",
"chậm vậy sao cứu được con đĩ mẹ mày nhanh lên đi chứ:)))  ",
"chết cha nó sồn r  ",
"con đĩ mẹ mày gào thét đê?😛  ",
"mày gào lên con?😏  ",
"sao cay tao dọ?  ",
"mày sủa đi nè😛  ",
"sao mày xấu lồn gớm chó dị con?  ",
"sao cay tao hả😏?  ",
"cái lồn mẹ m cạn ngôn r hả ? ",
"ra đây chơi với cha nè",
"rén rồi hả 😘",
"cha nói thật ",
"chơi với cha đi em😁😁",
"sao câm z em 🤣🤣",
"sợ cha à em",
"cha nói rồi",
"ửa ai chứ ửa cha ",
"là em sai lầm",
"rén rồi nói luon",
"sao m câm nín khi thấy t đó m😉",
"m đang khiếp hãi à😆🤔",
"tk ớt bede ơi lên đi tr oi",
"đụ mẹ m sủa lên đi",
"tk cặc m đang bú lồn mẹ đẻ à😢",
"coi nó kìa nứng ko😊",
"thk cặc óc cứt m sủa đi",
"đéo lên tao win nhé tk mặt lồnt",
"ê tht luonn sao nín như chó z ",
"ê nói thật luon thua thì thua đi ai cấm đâu",
"sao phải sợ tới mức mà ko nói đc luon z",
"đéo lên tao win nhé tk mặt lồn",
"m câm t chặt đầu ba má m liền nè",
"con chó ngu đuối kìa ae🤔",
"thật maa",
"gà mà đòi đú vs cha m hả tk cc",
"bất ổn à tk ngu oi 🐮",
"ê thằng ăn cặc",
"cha bá rõ mà m",
"nhanh nhẹn tý đê",
"sao m yếu z tk bede", 
"m câm t chặt đầu cha m liền đó🤣🤣",
"sủa mau cho cha m xem nè",
"ngửa lồn lên cho bố địt",
"sủa lẹ đi tk ngu",
"m óc cứt",
"à tk bại não",
"bede óc cứt cay cú à",
"con chó ngu",
"sủa liên tục đi 🤣",
"cay cú à sủa mạnh lên đê",
"nhục rồi à ?",
"m cx bit nhục ak",
"hài v",
"ê mà súc vật cx bit nhục á",
"cay cú à sủa mạnh lên đê",
"mày bần hèn vậy à thằng óc cứt",
"nói vói m mỏi hơn nhấp cu vào lồn mẹ m",
"m đang tập tành đánh vần từng câu từng chử 1 cho tao nghe à tk bede",
"sát thương tí đi dc kh 😜",
"nhìn mày phèn phèn bẩn bẩn",
"sao m nghịch tử vậy tk não cao su",
"sao m nghịch tử vậy tk não cao su",
"ới con lợn này ảo ửa kìa",
"con gà mà cứ đòi ửa",
"sao hả cay r à",
"thuaa",
"sao vậy em",
"địt mẹ m sủa lên",
"cần anh chỉ dạy m cách nhây kh tk óc chó", 
"Óc lồn ảo ửa đâu hả",
"cái lồn mẹ m sủa mạnh lên",
"vãi cả bại lồn",
"m óc rõ mà m xạo lồn vs cha à con chó ngu",
"tk bê đê não cứt cay cú anh kiểu",
"gi thế tk ngu chó con", 
"gi thế tk ngu chó con", 
"sủa hăng lên con chó ngu",
"sao mày giết mẹ vậy=)))  ",
"mày gào đi con=)))  ",
"nào ổn thì đú🤣👈  ",
"ê bê đê lên ăn hôi lẹ😘  ",
"mày đú rõ mò  ",
"sao mày ăn cứt tao😏  ",
"ai cho mày ăn cứt tao  ",
"sao mày óc cặc dữ con=)))  ",
"gặp tao đừng run nha?😂  ",
"con đĩ mẹ mày thèm cứt tao dữ lắm=)))  ",
"mày mồ côi mà đúng k🤣👈  ",
"ai cho mày sủa tao cho mày sủa chưa?  ",
"bị tao chọc cay hơn con chó luôn=)))  ",
"cố đi sắp win rồi nè😏  ",
"chừng nào mày mới làm lại tao dị?  ",
"mẹ mày sắp tắt thở kìa ê  ",
"đậu má mày gà mà sủa  ",
"sủa điên đi mà sủa hăng lên mới vui😘  ",
"mày mà ngưng một giây là con đĩ mẹ mày bả tắt đường thở á😏  ",
"ê chó ngu mày sợ tao hả😂  ",
"mày đú rõ mà sao mày đú dị?  ",
"mẹ mày chết chưa con=)))  ",
"ê bê đê sủa điên đi  ",
"sao mày sủa chậm dị?  ",
"nào làm lại tao nói đê?  ",
"bị tao chọc cay hơn con chó luôn😏  ",
"sủa đi rồi tao tha?  ",
  "sồn hăng lên em",
"sao m yếu v",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí eii",
"k đc à",
"con eii cố de",
"sao m câm kìa",
"gà j",
"phãn kháng đi con chó",
"cha bá sàn cmnr tk sủa mạnh lên dc k chó",
"tk ớt cay kiểu",
"đúng mà",
"m hoản loạn khi gặp cha à",
"mày còn gì khác k",
"gà mà m xạo lồn vs cha m à",
"tk súc sinh",
"mếu à",
"đầu đình tứ phủ",
"bị a đá lên đầu lên cổ",
"va lẹ eii",
"sao kìa",
"từ bỏ r à",
"nhìn a",
"phập lồn con gái mẹ m",
"m bất lực",
"kh lm j dc anh",
"sao mày bất lực để anh hành hạ vậy hả con chó ngu =))))",
"cay lắm phải kh",
"đúng k",
"tk não chó",
"m liếm lồn dê khen béo à",
"tk óc heo",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"tk óc heo",
"mày nghĩ mày làm t cay đc à",
"m chỉ bt ngồi",
"tao đang hành m mà",
"rênh rỉ gào thét",
"trong vô vọng à",
"tk giả gái sủa hăng lên",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"sồn mạnh lên",
"chửi như m đéo ai nghe",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"nó treo à ae 🤣",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh eii",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
    "chó ăn cứt cay 🤣🤣",
"sủa đê 🤣🤣",
"chó bú cứt🤣🤣",
"hăng hái đê :))",
"chậm dọ 🤣🤣",
"óc dái cay r🤣🤣",
"ăn hại phát biểu lẹ đê 🤣🤣",
"óc dái :)))",
"ổn phải k?",
"ngu ớn 🤣🤣👌",
"chó ăn cứt 🐶",
"dái đú :))))",
"yếu dữ ta😏😏",
"con chó đần👉🤣",
"ổn dữ chưa =)))",
"run ớn dạ :)))",
"óc đú 🤣🤣",
"rồi xong 🤢🤢",
"có thể hăng ko á ",
"ẻm cay doài =)))",
"cay tuột buồi 👉",
"ei ei =))",
"em ei :3",
"chạy à",
"mày sợ hả 🤢🤢",
"coi ẻm sồn kìa🤣🤣 ",
"lại bá à :)))",
"sao chậm dữ",
"eo oyyy:3",
"hú hú🤨",
"sao ức chế dạ 😏😏",
"con não cún bị chửi kìa 🤣🤣🐶",
"mau đê :))",
"hăng đê :)))",
"sủa mau đê =))",
"cần cứu ko :))",
"cố đi :3",
"gáng lên đê :)))",
"sủa to lên🤣🤣",
"chửi như a thì hàng ngàng người nghe 🤢🤢",
"khi m thấy a nhây =))))",
"khoẻ ko 🤣🤣",
"kkk",
"đói à🤣🐶👌",
"cx ch thấy anh m rớt",
"khỏi có xạo lồn vs t đâu tk tầm hồn chó dại m bị a chửi đến nổi kh kịp đầu thai à:)))",
"thấy kém cõi :))",
"đú cứt kìa :)))",
"bị a chửi đến nổi con đĩ mẹ m dựt mồng chết đi sống lại kh kịp à",
"cố đê 🤣🤣",
"thấy mày đơ đơ :)))",
"con cave 🤣🤣",
"mạnh lên:)))",
"gõ mạnh lên đê:))",
"thấy ngại ngùng z🤣🤘",
"tự nhiên đê",
"mệt đk",
"cấm m ngưng",
"đĩ đầu đinh :)))",
"lẹ đê:))",
"mày lag à :))",
"m trầm cảm à :)))",
"tâm lí ko vững à :))",
"cần thuốc à :))",
"hấp hối hả🤣🤣",
"khó thở dk :))",
"cần oxi ko :)))",
"mày bệnh nặng lắm à :)))",
"tuột hứng cha :)))",
"tnh gà :)))",
"sao chậm chạp v :))",
"óc dái 🤣🤣",
"lồn cụ con đĩ đớ🤣🤣",
"lưu loát lên đê 🤣🤣",
"khựng dạ :)))",
"t mạnh lắm phải ko à :)))",
":))) nhỏ mếu à ae",
"m nghèo mà",
"sợ t lắm à:3",
"hả cu =)))",
"thấy tội quá:))",
"thương ẻm cố gắng🤢🤘",
"mà ngu🤣🤣",
":)) 🤣🤣",
"cay lắm à :))",
"nhạt nhoè v à",
"ko cảm hứng để hăng à :)))",
"xạo lồn à :)))",
"khóc đk :)))",
"cave tỉnh lẽ phát biểu:))",
"ra tín hiệu đê :)))",
"SOS con dái đú 🤣🤣🤢",
"ớ ớ ớ :)))",
"chó ăn cứt :)))",
"chó đú sàn 👌🐶",
"ỉa ra máu r à :)))",
"nghèo k có nghi lực à:))",
"phản kháng đê :))) t win à",
"kkk",
"m chết r à :)))",
"m nghèo mà em 😏🤣",
"m thèm cứt t mà:))",
"đĩ mẹ m ngu mà👉🤣",
"m cay tao mà :))",
"con óc cứt thối🤢🤢",
"con đĩ mặt chim🤪🤪",
"ôm hận à 🤨",
"con đĩ nhà núi :)))",
"bede bóng lộ =))",
"cn đĩ mẹ mày",
"tao từ hình mẹ m mà :))",
"tk phế vật ăn hại😏🤘",
"đú đởn hả con :))",
"m sao dọ",
"sủa nè ",
"123 sủa😏",
"lẹ nè ",
"alo alo hú hú ",
"th cầm thú",
"m s dạ ",
"m sợ mẹ hả ",
"lên đi mẹ ko giết cha má m đâu mà 😏",
"hù :))",
"bất ổn hở",
"s đó ",
"m rớt kìa th gà🤪",
"t cấm m chối nhen",
"chối t giết cha má m nè:)))",
"hăng xíu lẹ kaka🤢",
"th đần ",
"lên mẹ biểu",
"k lên t tuyệt chủng m nhen cn thú",
"m thích đú ko dạ🤨",
"ko rep = t win nhen ",
"cấm chạy nhen",
"m mau ",
"lên đây ơ ơ ",
"th ngu ê",
"s á lên đây mẹ sút m chết",
"m khóc à 👉🤣",
"sủa liên tục ơ🤣🤣",
"cầu cứu lũ đú à ",
"sục dái nó xem à",
"dái thâm v?",
"chậm v cn culi🤣🤣👌",
"hoảng loạn à",
"bất ổn à 🤮🤮",
"run à",
"chạy à ",
"đuối à ",
"bại chưa 👉😏",
"sủa mau🙄🙄👈",
"mạnh dạn lên ",
"nhanh t cho cơ hội cứu má m nè",
"cấm mách mẹ",
"ảo war hở :))",
"dồn ko ",
"đua nè lên sàn t chấp😏👌",
"th chợ búa m sao v",
"th đầu buồi mặt chó😢🫵🏻👈🏻",
"cấm hoảng loạn",
"lại phải win nữa à🙄🙄",
"sủa điên lên cho mẹ?  ",
"mày ngưng là con đĩ mẹ mày chết?  ",
"cay tao lòi dái hả😏  ",
"não chó cay à?🤣  ",
"sao mày thảm dị=)))  ",
"mẹ mày bị tao địt rách màn trinh mà🤪  ",
"mẹ mày bị tao dã vào lồn=)))  ",
"địt mẹ mày sướng tê con cặc=)))  ",
"huhu nhìn mày như con cặc=)))  ",
"mày loạn luân bà già hả=)))  ",
"mẹ mày bị tao địt rên ư ử=)))  ",
"địt mẹ mày sảng khoái quá đi😛  ",
"tao địt mẹ mày nát lồn mà=)))  ",
"Ê bóng lồn  ",
  "sao m yếu v",
"cố tí nữa",
"sao kìa chậm à",
"hăng hái lên tí chứ",
"tới sáng đi em eii",
"cố gắng tí eii",
"k đc à",
"con eii cố de",
"sao m câm kìa",
"gà j",
"tnh gà",
"m gà mà",
"dk à",
"đúng mà",
"cãi à",
"mày còn gì khác k",
"học lỏm kìa",
"cố tí em",
"mếu à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"va lẹ eii",
"sao kìa",
"từ bỏ r à",
"mạnh mẽ tí đi nà",
"cố eii",
":)))",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"nó treo à ae 🤣",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"mẹ mày bị tao cưỡng hiếp=)))  ",
"mẹ mày đưa lồn chó liếm à🤣👈  ",
"mày óc cái lồn mà  ",
"năn nỉ đi tao tha😏  ",
"bú lồn tao đi🤪  ",
"mày ẳng gì dị?😏  ",
"nghe nói mày sợ tao?  ",
"vô danh cấm sủa?😏  ",
"gì mày thèm cứt tao hả=)))?  ",
"sao mày lề mề dị con  ",
"mày có tuổi hở?😏  ",
"tuổi lồn ăn tao á😏?  ",
  "sủa đê 🤣🤣 ",
"chó bú cứt🤣🤣👌",
"hăng hái đê :)) ",
"chậm dọ 🤣🤣 ",
"óc dái cay r🤣🤣 ",
"ăn hại phát biểu lẹ đê 🤣🤣 ",
"óc dái :))) ",
"ổn phải k? ",
"ngu ớn 🤣🤣👌 ",
"chó ăn cứt 🐶 ",
"dái đú :)))) ",
"yếu dữ ta😏😏 ",
"con chó đần👉🤣 ",
"ổn dữ chưa =))) ",
"run ớn dạ :))) ",
"óc đú 🤣🤣 ",
"rồi xong 🤢🤢 ",
"có thể hăng ko á  ",
"ẻm cay doài =))) ",
"cay tuột buồi 👉🤣",
"ei ei =)) ",
"em ei :3 ",
"chạy à ",
"mày sợ hả 🤢🤢 ",
"coi ẻm sồn kìa🤣🤣 👌",
"lại bá à :))) ",
"sao chậm dữ ",
"eo oyyy:3 ",
"hú hú🤨 ",
"sao ức chế dạ 😏😏 ",
"con não cún bị chửi kìa 🤣🤣🐶 ",
"mau đê :)) ",
"hăng đê :))) ",
"sủa mau đê =)) ",
"cần cứu ko :)) ",
"cố đi :3 ",
"gáng lên đê :))) ",
"sủa to lên🤣🤣 ",
"phò nông thôn 🤢🤢 ",
"óc cặc tỉnh lẽ =)))) ",
"khoẻ ko 🤣🤣 ",
"kkk ",
"đói à🤣🐶👌 ",
"ăn chưa à 🤣🤣 ",
"chưa đk :))) ",
"thấy kém cõi :)) ",
"đú cứt kìa :))) ",
"eo oyyy:3 ",
"cố đê 🤣🤣 ",
"thấy mày đơ đơ :))) ",
"con cave 🤣🤣 ",
"mạnh lên:))) ",
"gõ mạnh lên đê:)) ",
"thấy ngại ngùng z🤣🤘 ",
"tự nhiên đê ",
"mệt đk ",
"cấm m ngưng ",
"đĩ đầu đinh :))) ",
"lẹ đê:)) ",
"mày lag à :)) ",
"m trầm cảm à :))) ",
"tâm lí ko vững à :)) ",
"cần thuốc à :)) ",
"hấp hối hả🤣🤣 ",
"khó thở dk :)) ",
"cần oxi ko :))) ",
"mày bệnh nặng lắm à :))) ",
"tuột hứng cha :))) ",
"tnh gà :))) ",
"sao chậm chạp v :)) ",
"óc dái 🤣🤣 ",
"lồn cụ con đĩ đớ🤣🤣 ",
"lưu loát lên đê 🤣🤣 ",
"khựng dạ :))) ",
"t mạnh lắm phải ko à :))) ",
":))) nhỏ mếu à ae ",
"m nghèo mà ",
"sợ t lắm à:3 ",
"hả cu =))) ",
"thấy tội quá:)) ",
"thương ẻm cố gắng🤢🤘 ",
"mà ngu🤣🤣 ",
":)) 🤣🤣 ",
"cay lắm à :)) ",
"nhạt nhoè v à ",
"ko cảm hứng để hăng à :))) ",
"xạo lồn à :))) ",
"khóc đk :))) ",
"cave tỉnh lẽ phát biểu:)) ",
"ra tín hiệu đê :))) ",
"SOS con dái đú 🤣🤣🤢 ",
"ớ ớ ớ :))) ",
"chó ăn cứt :))) ",
"chó đú sàn 👌🐶 ",
"ỉa ra máu r à :))) ",
"nghèo k có nghi lực à:)) ",
"phản kháng đê :))) t win à ",
"kkk ",
"m chết r à :))) ",
"m nghèo mà em 😏🤣 ",
"m thèm cứt t mà:)) ",
"đĩ mẹ m ngu mà👉🤣 ",
"m cay tao mà :)) ",
"con óc cứt thối🤢🤢 ",
"con đĩ mặt chim🤪🤪 ",
"ôm hận à 🤨 ",
"con đĩ nhà núi :))) ",
"bede bóng lộ =)) ",
"cn đĩ mẹ mày ",
"tao từ hình mẹ m mà :)) ",
"tk phế vật ăn hại😏🤘 ",
"đú đởn hả con :)) ",
"m sao dọ ",
"sủa nè  ",
"123 sủa😏 ",
"lẹ nè  ",
"alo alo hú hú  ",
"th cầm thú ",
"m s dạ  ",
"m sợ mẹ hả  ",
"lên đi mẹ ko giết cha má m đâu mà 😏 ",
"hù :)) ",
"bất ổn hở ",
"s đó  ",
"m rớt kìa th gà🤪 ",
"t cấm m chối nhen ",
"chối t giết cha má m nè:))) ",
"hăng xíu lẹ kaka🤢 ",
"th đần  ",
"lên mẹ biểu ",
"k lên t tuyệt chủng m nhen cn thú ",
"m thích đú ko dạ🤨 ",
"ko rep = t win nhen  ",
"cấm chạy nhen ",
"m mau  ",
"lên đây ơ ơ  ",
"th ngu ê ",
"s á lên đây mẹ sút m chết ",
"m khóc à 👉🤣 ",
"sủa liên tục ơ🤣🤣 ",
"cầu cứu lũ đú à  ",
"sục dái nó xem à ",
"dái thâm v? ",
"chậm v cn culi🤣🤣👌 ",
"hoảng loạn à ",
"bất ổn à 🤮🤮 ",
"run à ",
"chạy à  ",
"đuối à  ",
"bại chưa 👉😏 ",
"sủa mau🙄🙄👈 ",
"mạnh dạn lên  ",
"nhanh t cho cơ hội cứu má m nè ",
"cấm mách mẹ ",
"ảo war hở :)) ",
"dồn ko  ",
"đua nè lên sàn t chấp😏👌 ",
"k đc à",
"con eii cố de",
"sao m câm kìa",
"gà j",
"tnh gà",
"m gà mà",
"dk à",
"đúng mà",
"cãi à",
"mày còn gì khác k",
"học lỏm kìa",
"cố tí em",
"mếu à",
"sao mếu kìa",
"tao đã cho m mếu đâu",
"va lẹ eii",
"sao kìa",
"từ bỏ r à",
"mạnh mẽ tí đi nà",
"cố eii",
":)))",
"sợ tao à",
"sao sợ tao kìa",
"cay lắm phải kh",
"ớt rồi kìa em",
"mày còn chối à",
"làm tí đê",
"mới đó đã mệt r kìa",
"sao gà mà sồn v",
"sồn như lúc đầu cho tao",
"sao à",
"ai cho m nhai",
"cay lắm r", 
"từ bỏ đi em",
"mày nghĩ mày làm t cay đc à",
"có đâu",
"tao đang hành m mà",
"bịa à",
"cay :)))))",
"cố eiii",
"hăng tiếp đi",
"tới sáng k em",
"k tới sáng à",
"chán v",
"m gà mà",
"log acc thay phiên à",
"coi tụi nó dồn ngu kìa",
"ae ơiii",
"lại win à",
"lại win r",
"lũ cặc cay tao lắm🤣🤣",
"cố lên đê",
"nó treo à ae 🤣",
"yếu đến thế à",
"sao kìa",
"khóc kìa",
"cầu cứu lẹ ei",
"ai cứu đc m à :))",
"tao bá mà",
"sao m gà thế",
"hăng lẹ cho tao",
"con chó eiii🤣",
"ổn k em",
"kh ổn r à",
"xin tha eii",
"mẹ mày ngu à",
"bú cặc cha m k em",
"thg giả gái :))",
"coi nó ngu kìa ae",
"con chó này giả ngu à",
"m ổn k",
"mồ côi kìa",
"sao v sợ r à",
"cố gắng tí em",
"cay cú lắm r",
"đấy đấy bắt đầu",
"chảy nước đái bò r à em",
"sao kìa đừng run",
"mày run à:))",
"thg dái lở",
"cay mẹ m lắm",
"lgbt xuất trận ae eii",
"thg cặc giết cha mắng mẹ",
"sủa mạnh eii",
"mày chết r à:))",
"sao chết kìa",
"bị t hành nên muốn chết à",
"con lồn ngu=))",
"sao kìa",
"mạnh lên kìa",
"yếu sinh lý à",
  "sủa đê",
"cay à",
"hăng đê",
"gà kìa ae",
"akakaa",
"óc chó kìa",
"🤣🤣🤣",
"ổn không🤣🤣",
"bất ổn à",
"ơ kìaaa",
"hăng hái đê",
"chạy à 🤣🤣",
"tởn à",
"kkkk",
"mày dốt à",
"cặc ngu",
"cháy đê",
"chat hăng lên",
"cố lên",
"mồ côi cay",
"cay à",
"cn chó ngu",
"óc cặc kìa",
"đĩ đú:))",
"đú kìa",
"cùn v",
"r x",
"hhhhh",
"kkakak",
"sao đú",
"cặc con",
"ngu kìa",
"chat mạnh đê",
"hăng ee",
"ơ ơ ơ",
"sủa cháy đê",
"sủa mạnh eei",
    "chó ăn cứt cay 🤣🤣",
"sủa đê 🤣🤣",
"chó bú cứt🤣🤣",
"hăng hái đê :))",
"chậm dọ 🤣🤣",
"óc dái cay r🤣🤣",
"ăn hại phát biểu lẹ đê 🤣🤣",
"óc dái :)))",
"ổn phải k?",
"ngu ớn 🤣🤣👌",
"chó ăn cứt 🐶",
"dái đú :))))",
"yếu dữ ta😏😏",
"con chó đần👉🤣",
"ổn dữ chưa =)))",
"run ớn dạ :)))",
"óc đú 🤣🤣",
"rồi xong 🤢🤢",
"có thể hăng ko á ",
"ẻm cay doài =)))",
"cay tuột buồi 👉",
"ei ei =))",
"em ei :3",
"chạy à",
"mày sợ hả 🤢🤢",
"coi ẻm sồn kìa🤣🤣 ",
"lại bá à :)))",
"sao chậm dữ",
"eo oyyy:3",
"hú hú🤨",
"sao ức chế dạ 😏😏",
"con não cún bị chửi kìa 🤣🤣🐶",
"mau đê :))",
"hăng đê :)))",
"sủa mau đê =))",
"cần cứu ko :))",
"cố đi :3",
"gáng lên đê :)))",
"sủa to lên🤣🤣",
"phò nông thôn 🤢🤢",
"óc cặc tỉnh lẽ =))))",
"khoẻ ko 🤣🤣",
"kkk",
"đói à🤣🐶👌",
"ăn chưa à 🤣🤣",
"chưa đk :)))",
"thấy kém cõi :))",
"đú cứt kìa :)))",
"eo oyyy:3",
"cố đê 🤣🤣",
"thấy mày đơ đơ :)))",
"con cave 🤣🤣",
"mạnh lên:)))",
"gõ mạnh lên đê:))",
"thấy ngại ngùng z🤣🤘",
"tự nhiên đê",
"mệt đk",
"cấm m ngưng",
"đĩ đầu đinh :)))",
"lẹ đê:))",
"mày lag à :))",
"m trầm cảm à :)))",
"tâm lí ko vững à :))",
"cần thuốc à :))",
"hấp hối hả🤣🤣",
"khó thở dk :))",
"cần oxi ko :)))",
"mày bệnh nặng lắm à :)))",
"tuột hứng cha :)))",
"tnh gà :)))",
"sao chậm chạp v :))",
"óc dái 🤣🤣",
"lồn cụ con đĩ đớ🤣🤣",
"lưu loát lên đê 🤣🤣",
"khựng dạ :)))",
"t mạnh lắm phải ko à :)))",
":))) nhỏ mếu à ae",
"m nghèo mà",
"sợ t lắm à:3",
"hả cu =)))",
"thấy tội quá:))",
"thương ẻm cố gắng🤢🤘",
"mà ngu🤣🤣",
":)) 🤣🤣",
"cay lắm à :))",
"nhạt nhoè v à",
"ko cảm hứng để hăng à :)))",
"xạo lồn à :)))",
"khóc đk :)))",
"cave tỉnh lẽ phát biểu:))",
"ra tín hiệu đê :)))",
"SOS con dái đú 🤣🤣🤢",
"ớ ớ ớ :)))",
"chó ăn cứt :)))",
"chó đú sàn 👌🐶",
"ỉa ra máu r à :)))",
"nghèo k có nghi lực à:))",
"phản kháng đê :))) t win à",
"kkk",
"m chết r à :)))",
"m nghèo mà em 😏🤣",
"m thèm cứt t mà:))",
"đĩ mẹ m ngu mà👉🤣",
"m cay tao mà :))",
"con óc cứt thối🤢🤢",
"con đĩ mặt chim🤪🤪",
"ôm hận à 🤨",
"con đĩ nhà núi :)))",
"bede bóng lộ =))",
"cn đĩ mẹ mày",
"tao từ hình mẹ m mà :))",
"tk phế vật ăn hại😏🤘",
"đú đởn hả con :))",
"m sao dọ",
"sủa nè ",
"123 sủa😏",
"lẹ nè ",
"alo alo hú hú ",
"th cầm thú",
"m s dạ ",
"m sợ mẹ hả ",
"lên đi mẹ ko giết cha má m đâu mà 😏",
"hù :))",
"bất ổn hở",
"s đó ",
"m rớt kìa th gà🤪",
"t cấm m chối nhen",
"chối t giết cha má m nè:)))",
"hăng xíu lẹ kaka🤢",
"th đần ",
"lên mẹ biểu",
"k lên t tuyệt chủng m nhen cn thú",
"m thích đú ko dạ🤨",
"ko rep = t win nhen ",
"cấm chạy nhen",
"m mau ",
"lên đây ơ ơ ",
"th ngu ê",
"s á lên đây mẹ sút m chết",
"m khóc à 👉🤣",
"sủa liên tục ơ🤣🤣",
"cầu cứu lũ đú à ",
"sục dái nó xem à",
"dái thâm v?",
"chậm v cn culi🤣🤣👌",
"hoảng loạn à",
"bất ổn à 🤮🤮",
"run à",
"chạy à ",
"đuối à ",
"bại chưa 👉😏",
"sủa mau🙄🙄👈",
"mạnh dạn lên ",
"nhanh t cho cơ hội cứu má m nè",
"cấm mách mẹ",
"ảo war hở :))",
"dồn ko ",
"đua nè lên sàn t chấp😏👌",
"th chợ búa m sao v",
"th đầu buồi mặt chó😢🫵🏻👈🏻",
"cấm hoảng loạn",
"lại phải win nữa à🙄🙄",
"sao thế tk não phẳng",
"kkk"
];

let index = 0;
let isStopped = false;

export function onCall({ message }) {
  const args = message.body.split(" ").slice(1); 
  if (args[0] === "stop") {
    isStopped = true; 
    message.send("𝗡𝗧𝗣 𝒃𝒂́ 𝒏𝒉𝒂̂𝒚 𝒎𝒂̀ 𝒍𝒖̃ 𝒏𝒈𝒖𝒖 👈🤪");
    return;
  }

  if (isStopped) {
    isStopped = false;
  }

  const sendText = () => {
    message.send(list[index]);
    index = (index + 1) % list.length;
    if (!isStopped) {
      setTimeout(sendText, 3700); 
    }
  };
  sendText();
}

export default {
  config,
  onCall
};